# Generated by Django 5.2.1 on 2025-05-17 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('romantic', 'Romantic'), ('festive', 'Festive'), ('casual', 'Casual')], default='festive', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('gift', 'Gift'), ('romantic_dinner', 'Romantic Dinner'), ('celebration', 'Celebration')], default='romantic_dinner', max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='wine',
            options={'verbose_name': 'Wine', 'verbose_name_plural': 'Wines'},
        ),
        migrations.RemoveField(
            model_name='wine',
            name='info',
        ),
        migrations.AddField(
            model_name='wine',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('white', 'White'), ('rose', 'Rose')], default='red', max_length=20),
        ),
        migrations.AddField(
            model_name='wine',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wine',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wine',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wine',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wine',
            name='price_range',
            field=models.CharField(choices=[('budget', 'Budget'), ('mid-range', 'Mid Range'), ('premium', 'Premium')], default='budget', max_length=20),
        ),
        migrations.AddField(
            model_name='wine',
            name='producer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wine',
            name='wine_type',
            field=models.CharField(choices=[('dry', 'Dry'), ('semi_dry', 'Semi Dry'), ('semi_sweet', 'Semi Sweet'), ('dessert', 'Dessert'), ('sparkling', 'Sparkling')], default='dessert', max_length=20),
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.wine')),
            ],
        ),
        migrations.AddField(
            model_name='wine',
            name='moods',
            field=models.ManyToManyField(blank=True, to='shop.mood'),
        ),
        migrations.AddField(
            model_name='wine',
            name='occasions',
            field=models.ManyToManyField(blank=True, to='shop.occasion'),
        ),
    ]
