# Generated by Django 5.2.1 on 2025-05-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('wine', 'Wine'), ('glass', 'Glass'), ('corkscrew', 'Corkscrew')], default='wine', max_length=20),
        ),
        migrations.DeleteModel(
            name='TypeOfProduct',
        ),
    ]
